[JavaScript] add sergiomario/perfil-politico
jtemporal/jtemporal.github.io pull request #127
Opened 2021-10-02 16:52 UTC by di3goCS

2021-10-02 20:58 UTC, jtemporal requested changes
@di3goCS seguem as alterações que precisam ser feitas 😉 corrigindo elas eu aprovo o PR

2021-10-02 20:58 UTC, jtemporal commented on _hacktoberfest_projects/JavaScript/sergiomario+perfil-politico.md
> +repo: https://github.com/sergiomario/perfil-politico
```suggestion
repo: https://github.com/okfn-brasil/perfil-politico
```

2021-10-02 20:58 UTC, jtemporal commented on _hacktoberfest_projects/JavaScript/sergiomario+perfil-politico.md
> +image: https://avatars.githubusercontent.com/u/2698516?s=120&v=4
```suggestion
image: https://avatars.githubusercontent.com/u/1666382?s=200&v=4
```

2021-10-02 21:07 UTC, di3goCS commented
Correções realizadas :D

2021-10-03 10:07 UTC, jtemporal approved these changes
👍

2021-10-03 10:07 UTC, merged