Adicionando projeto "Crudificator"
jtemporal/jtemporal.github.io pull request #13
Opened 2019-10-01 14:04 UTC by simonardejr

2019-10-02 17:57 UTC, jtemporal requested changes
Oi Simonarde! Pode colocar a extensão .md no nome do arquivo! Com essa pequena correção eu aprovo e dou merge! Obrigada pelo PR!

2019-10-02 18:00 UTC, jtemporal commented
Outro ponto importante: seu projeto não possui issues abertas. Você pretende abri-las?

2019-10-02 21:03 UTC, simonardejr commented
Olá! Acabei de ajustar o nome do arquivo conforme você indicou! Sobre as issues, vou abri-las lá também :) Valeu!

2019-10-03 23:36 UTC, jtemporal approved these changes

2019-10-03 23:37 UTC, merged