Python
jtemporal/jtemporal.github.io pull request #136
Opened 2021-10-04 21:45 UTC by rayanepimentel

This is Querido Diário's API. It provides everything the frontend does and even more!

2021-10-06 02:15 UTC, jtemporal requested changes

2021-10-06 02:15 UTC, jtemporal commented on _hacktoberfest_projects/Ruby/juu42dias+transervicos.md
> +---
esse projeto ja existe na pasta Ruby, pode remover-lo para que eu possa aceitar o PR?

2021-10-06 02:16 UTC, jtemporal requested changes

2021-10-06 02:16 UTC, jtemporal commented on _hacktoberfest_projects/Python/okfn-brasil +querido-diario-api.md
> +---
Por favor também remover o espaço em branco antes do `+` no nome do arquivo

2021-10-13 13:05 UTC, jtemporal commented
@rayanepimentel Obrigada pela sua contribuição, mas estou fechando esse pull request por inatividade. Por favor submeta novamente o pr com as correções 😉

2021-10-13 13:05 UTC, closed without merging

2021-10-13 13:22 UTC, rayanepimentel commented on _hacktoberfest_projects/Python/okfn-brasil +querido-diario-api.md
> +---
@jtemporal desculpa, por algum motivo só recebi suas mensagens hoje. Vou refazer isso. Obrigada e desculpa.