Adicionando minigame "Matador de Monstros"
jtemporal/jtemporal.github.io pull request #15
Opened 2019-10-01 15:01 UTC by simonardejr

2019-10-02 18:04 UTC, jtemporal requested changes
Olá Simonarde! Seu projeto não possui issues abertas, você pretende abri-las? Para entrar na lista os projetos precisam ter pelo menos uma issue. Além disso precisaria também acrescentar a extensão no arquivo .md

2019-10-02 21:15 UTC, simonardejr commented
Olá! Pronto, acabei de alterar a extensão e abrir a issue :D Valeu!

2019-10-03 23:34 UTC, jtemporal commented on _hacktoberfest_projects/JavaScript/simonardejr+matador-de-monstros.md
> +principal_language: Javascript
```suggestion
principal_language: JavaScript
```

2019-10-03 23:35 UTC, jtemporal requested changes
Por favor aceite a sugestão @simonardejr eu estou sem permissão para tanto ;)

2019-10-10 19:54 UTC, merged