[Variados] ORI-project made in c++
jtemporal/jtemporal.github.io pull request #39
Opened 2019-10-05 13:13 UTC by perebaj

initial committ

2019-10-05 21:50 UTC, jtemporal requested changes
Oi! Além do link que precisa de correção, é necessária mais duas alterações:

1. Que esse arquivo tenha uma extensão .md
1. Que o projeto possua issues abertas
1. Que esteja na pasta correspondente a linguagem principal do projeto

2019-10-05 21:50 UTC, jtemporal commented on _hacktoberfest_projects/Variados/ORI-Project+jj_neno
> +repo: https://github.com/perebaj/ufsh/tree/cpp
O link do repo não deve conter subdiretórios. Pode corrigir?

2019-10-06 21:51 UTC, perebaj commented on _hacktoberfest_projects/Variados/ORI-Project+jj_neno
> +repo: https://github.com/perebaj/ufsh/tree/cpp
Como assim, subdiretórios?
Sobre o req 3. Apenas estou trabalhando na branch cpp, que foi o link q enviei. Onde o projeto está sendo desenvolvido em C++
Req 2. Vou providenciar
Req 1. Qual arquivo deve ter essa extensão?

2019-10-06 23:49 UTC, jtemporal commented on _hacktoberfest_projects/Variados/ORI-Project+jj_neno
> +repo: https://github.com/perebaj/ufsh/tree/cpp
subdiretorios sao todas as coisas depois do dominio principal... mas nesse caso em particular me referi ao `tree/cpp`, basta remover essa parte do link do repositorio. Ainda sobre o 3 mesmo que seja uma branch particular que você esta trabalhando a linguagem principal do projeto é C, entao o projeto deve estar na pasta C e nao na pasta de variados. Sem essa correção e sem issues abertas esse PR não poderá ser aprovado =)

2019-11-16 13:37 UTC, closed without merging