Adding corcel project to php list
jtemporal/jtemporal.github.io pull request #40
Opened 2019-10-07 20:06 UTC by eudiegoborgs

2019-10-07 20:29 UTC, jtemporal requested changes

2019-10-07 20:29 UTC, jtemporal commented on _hacktoberfest_projects/PHP/corcel.md
> +repo: https://github.com/corcel
esse nao eh um projeto o ideal seria acrescentar apenas um dos projetos.

2019-10-07 20:39 UTC, eudiegoborgs commented
Desculpe, coloquei o link errado

2019-10-09 22:12 UTC, jtemporal requested changes
Pode corrigir o nome do arquivo para ser guie o padrão dos demais?

2019-10-13 15:50 UTC, eudiegoborgs commented
Feito

2019-10-15 14:17 UTC, merged