[Variados] Add empresasqueusamreactnobrasil
jtemporal/jtemporal.github.io pull request #43
Opened 2019-10-09 17:05 UTC by claudiuri

2019-10-09 22:16 UTC, jtemporal requested changes

2019-10-09 22:16 UTC, jtemporal commented on _hacktoberfest_projects/Variados/react-brasil+empresas-que-usam-react-no-brasil.md
> +image: No image
Pode corrigir o link da imagem?

https://avatars2.githubusercontent.com/u/16929016?s=200&v=4

2019-10-09 23:49 UTC, claudiuri commented on _hacktoberfest_projects/Variados/react-brasil+empresas-que-usam-react-no-brasil.md
> +image: No image
posso sim !

2019-10-09 23:50 UTC, claudiuri reviewed
Imagem atualizada

2019-10-10 00:53 UTC, jtemporal approved these changes

2019-10-10 00:53 UTC, merged