[TypeScript] Add brazilian-utils/brazilian-utils
jtemporal/jtemporal.github.io pull request #44
Opened 2019-10-09 17:09 UTC by claudiuri

2019-10-09 22:15 UTC, jtemporal requested changes

2019-10-09 22:15 UTC, jtemporal commented on _hacktoberfest_projects/TypeScript/brazilian-utils+brazilian-utils.md
> +image: No image
Por favor corrige o link para imagem? Aí eu dou o merge :)

https://avatars0.githubusercontent.com/u/40146460?s=200&v=4

2019-10-09 23:51 UTC, claudiuri commented on _hacktoberfest_projects/TypeScript/brazilian-utils+brazilian-utils.md
> +image: No image
posso sim!

2019-10-09 23:52 UTC, claudiuri reviewed
Imagem atualizada

2019-10-10 00:53 UTC, jtemporal approved these changes

2019-10-10 00:54 UTC, merged